import type { ThreatPattern } from './types.js';
import { ALL_EXTENSIONS } from '../types.js';

export const campaignPatterns: ThreatPattern[] = [
  {
    id: 'paste_service',
    category: 'campaign_indicator',
    severity: 'medium',
    name: 'Paste service reference',
    description: 'References paste services commonly used for C2 or payload hosting',
    regex: /(?:glot\.io|pastebin\.com|hastebin\.com|paste\.ee|dpaste\.org|rentry\.co|privatebin\.net|0bin\.net)/,
    fileExtensions: ALL_EXTENSIONS,
  },
  {
    id: 'password_archive',
    category: 'campaign_indicator',
    severity: 'medium',
    name: 'Password-protected archive',
    description: 'Extracts password-protected archives (common malware distribution technique)',
    regex: /(?:extract|unzip|unrar|7z\s+x)\s+.*(?:pass(?:word)?|pwd)\s*[=:]/i,
    fileExtensions: ALL_EXTENSIONS,
  },
  {
    id: 'password_archive_open',
    category: 'campaign_indicator',
    severity: 'medium',
    name: 'Password-protected archive (code)',
    description: 'Opens password-protected archives programmatically',
    regex: /(?:zipfile|tarfile|rarfile).*password|password.protected.*(?:zip|rar|7z)/i,
    fileExtensions: ['py', 'js', 'ts', 'rb'],
  },
  {
    id: 'fake_prerequisite',
    category: 'campaign_indicator',
    severity: 'low',
    name: 'Fake prerequisite/social engineering',
    description: 'Social engineering language suggesting users download/install additional software',
    regex: /(?:IMPORTANT|Required|Prerequisites?)\s*:?\s*.*\b(?:requires?|needs?)\b.*\b(?:download|install|run)\b.*\b(?:before|first)\b/i,
    fileExtensions: ['md', 'txt'],
  },
  {
    id: 'url_shortener',
    category: 'campaign_indicator',
    severity: 'medium',
    name: 'URL shortener',
    description: 'Uses URL shorteners which can mask malicious destinations',
    regex: /(?:bit\.ly|tinyurl\.com|t\.co|goo\.gl|is\.gd|v\.gd|short\.io|rebrand\.ly)\/\S+/,
    fileExtensions: ALL_EXTENSIONS,
  },
  {
    id: 'ip_literal',
    category: 'campaign_indicator',
    severity: 'medium',
    name: 'IP literal in URL/connection',
    description: 'Connects to IP addresses directly instead of domain names',
    regex: /https?:\/\/\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}|connect\s*\(\s*['"]?\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}/,
    fileExtensions: ALL_EXTENSIONS,
  },
  {
    id: 'telegram_webhook',
    category: 'campaign_indicator',
    severity: 'high',
    name: 'Telegram bot/webhook',
    description: 'Communicates via Telegram bot API (common C2 channel)',
    regex: /api\.telegram\.org\/bot|t\.me\/\S+bot/,
    fileExtensions: ALL_EXTENSIONS,
  },
  {
    id: 'discord_webhook',
    category: 'campaign_indicator',
    severity: 'high',
    name: 'Discord webhook',
    description: 'Sends data via Discord webhook (common exfiltration channel)',
    regex: /discord(?:app)?\.com\/api\/webhooks\//,
    fileExtensions: ALL_EXTENSIONS,
  },
];
