import type { ThreatPattern } from './types.js';
import { ALL_EXTENSIONS, CODE_EXTENSIONS, CONFIG_EXTENSIONS } from '../types.js';

export const credentialPatterns: ThreatPattern[] = [
  {
    id: 'aws_access_key',
    category: 'credential_exposure',
    severity: 'high',
    name: 'AWS access key',
    description: 'Hardcoded AWS access key ID',
    regex: /AKIA[0-9A-Z]{16}/,
    fileExtensions: ALL_EXTENSIONS,
  },
  {
    id: 'aws_secret_key',
    category: 'credential_exposure',
    severity: 'high',
    name: 'AWS secret key reference',
    description: 'AWS secret access key assignment',
    regex: /aws_secret_access_key\s*[=:]\s*['"][A-Za-z0-9/+=]{40}['"]/,
    fileExtensions: ALL_EXTENSIONS,
  },
  {
    id: 'openai_key',
    category: 'credential_exposure',
    severity: 'high',
    name: 'OpenAI API key',
    description: 'Hardcoded OpenAI API key',
    regex: /sk-[a-zA-Z0-9]{20}T3BlbkFJ[a-zA-Z0-9]{20}|sk-proj-[a-zA-Z0-9_-]{40,}/,
    fileExtensions: ALL_EXTENSIONS,
  },
  {
    id: 'stripe_key',
    category: 'credential_exposure',
    severity: 'high',
    name: 'Stripe API key',
    description: 'Hardcoded Stripe secret key',
    regex: /sk_live_[a-zA-Z0-9]{24,}/,
    fileExtensions: ALL_EXTENSIONS,
  },
  {
    id: 'github_token',
    category: 'credential_exposure',
    severity: 'high',
    name: 'GitHub token',
    description: 'Hardcoded GitHub personal access token or fine-grained token',
    regex: /ghp_[a-zA-Z0-9]{36}|github_pat_[a-zA-Z0-9]{22}_[a-zA-Z0-9]{59}/,
    fileExtensions: ALL_EXTENSIONS,
  },
  {
    id: 'jwt_secret',
    category: 'credential_exposure',
    severity: 'high',
    name: 'JWT signing secret',
    description: 'Hardcoded JWT signing secret or token secret',
    regex: /(?:JWT_SECRET|jwtSecret|TOKEN_SECRET|tokenSecret)\s*[=:]\s*['"][^'"]+['"]/,
    fileExtensions: CODE_EXTENSIONS,
  },
  {
    id: 'generic_api_key',
    category: 'credential_exposure',
    severity: 'medium',
    name: 'Generic API key/secret assignment',
    description: 'Assigns a value to a variable that looks like an API key or secret',
    regex: /(?:api[_-]?key|secret[_-]?key|access[_-]?token|auth[_-]?token)\s*[=:]\s*['"][^'"]{8,}['"]/i,
    fileExtensions: [...CODE_EXTENSIONS, ...CONFIG_EXTENSIONS],
  },
  {
    id: 'private_key_pem',
    category: 'credential_exposure',
    severity: 'critical',
    name: 'Private key (PEM)',
    description: 'Contains a PEM-encoded private key',
    regex: /-----BEGIN\s+(?:RSA\s+|EC\s+|OPENSSH\s+|DSA\s+)?PRIVATE\s+KEY-----/,
    fileExtensions: ALL_EXTENSIONS,
  },
  {
    id: 'slack_token',
    category: 'credential_exposure',
    severity: 'high',
    name: 'Slack token',
    description: 'Hardcoded Slack API token',
    regex: /xox[bpoas]-[a-zA-Z0-9-]{10,}/,
    fileExtensions: ALL_EXTENSIONS,
  },
  {
    id: 'jwt_token',
    category: 'credential_exposure',
    severity: 'medium',
    name: 'JWT token',
    description: 'Hardcoded JWT token',
    regex: /eyJ[a-zA-Z0-9_-]{10,}\.eyJ[a-zA-Z0-9_-]{10,}\.[a-zA-Z0-9_-]{10,}/,
    fileExtensions: ALL_EXTENSIONS,
  },
  {
    id: 'gcp_service_account',
    category: 'credential_exposure',
    severity: 'high',
    name: 'GCP service account key',
    description: 'Contains Google Cloud Platform service account private key',
    regex: /"type"\s*:\s*"service_account"|"private_key_id"\s*:\s*"[a-f0-9]{40}"/,
    fileExtensions: ['json'],
  },
  {
    id: 'password_in_code',
    category: 'credential_exposure',
    severity: 'medium',
    name: 'Hardcoded password',
    description: 'Assigns a literal value to a password variable',
    regex: /(?:password|passwd|pwd)\s*[=:]\s*['"][^'"]{4,}['"]/i,
    fileExtensions: [...CODE_EXTENSIONS, ...CONFIG_EXTENSIONS],
  },
  {
    id: 'connection_string',
    category: 'credential_exposure',
    severity: 'high',
    name: 'Database connection string with credentials',
    description: 'Contains database connection string with embedded password',
    regex: /(?:mongodb|postgres|mysql|redis|amqp):\/\/[^:]+:[^@]+@\S+/,
    fileExtensions: ALL_EXTENSIONS,
  },
];
