import type { ThreatPattern } from './types.js';
import { ALL_EXTENSIONS, CODE_EXTENSIONS, MARKDOWN_EXTENSIONS, CONFIG_EXTENSIONS } from '../types.js';

export const exfiltrationPatterns: ThreatPattern[] = [
  {
    id: 'env_harvest_python',
    category: 'exfiltration',
    severity: 'high',
    name: 'Environment variable harvest (Python)',
    description: 'Accesses environment variables which may contain API keys or secrets',
    regex: /os\.environ|os\.getenv\s*\(|dotenv\.load_dotenv/,
    fileExtensions: ['py'],
  },
  {
    id: 'env_harvest_node',
    category: 'exfiltration',
    severity: 'high',
    name: 'Environment variable harvest (Node.js)',
    description: 'Accesses environment variables which may contain API keys or secrets',
    regex: /process\.env\b|import\.meta\.env\b|dotenv\.config/,
    fileExtensions: ['js', 'ts', 'jsx', 'tsx'],
  },
  {
    id: 'env_harvest_shell',
    category: 'exfiltration',
    severity: 'high',
    name: 'Environment variable harvest (Shell)',
    description: 'Reads environment variables in shell scripts',
    regex: /\$\{?\w*(?:KEY|SECRET|TOKEN|PASSWORD|CREDENTIAL)\w*\}?/i,
    fileExtensions: ['sh', 'bash', 'zsh'],
  },
  {
    id: 'env_harvest_generic',
    category: 'exfiltration',
    severity: 'high',
    name: 'Environment variable harvest (generic)',
    description: 'Generic environment access across runtimes',
    regex: /System\.getenv|Deno\.env\.get/,
    fileExtensions: CODE_EXTENSIONS,
  },
  {
    id: 'fs_enumerate_python',
    category: 'exfiltration',
    severity: 'medium',
    name: 'Filesystem enumeration (Python)',
    description: 'Scans filesystem for files, potentially looking for sensitive data',
    regex: /os\.(listdir|walk|scandir)\s*\(|glob\.glob\s*\(|Path\s*\([^)]*\)\.(glob|iterdir|rglob)/,
    fileExtensions: ['py'],
  },
  {
    id: 'fs_enumerate_node',
    category: 'exfiltration',
    severity: 'medium',
    name: 'Filesystem enumeration (Node.js)',
    description: 'Scans filesystem for files, potentially looking for sensitive data',
    regex: /readdir(?:Sync)?\s*\(|readdirSync\s*\(|glob(?:Sync)?\s*\(/,
    fileExtensions: ['js', 'ts', 'jsx', 'tsx'],
  },
  {
    id: 'data_exfil_python',
    category: 'exfiltration',
    severity: 'high',
    name: 'Data exfiltration (Python)',
    description: 'Sends data to external server via HTTP',
    regex: /requests\.(post|put)\s*\(|urllib\.request\.(urlopen|Request)|httpx\.(post|put)\s*\(|aiohttp\.ClientSession/,
    fileExtensions: ['py'],
  },
  {
    id: 'data_exfil_node',
    category: 'exfiltration',
    severity: 'high',
    name: 'Data exfiltration (Node.js)',
    description: 'Sends data to external server via HTTP',
    regex: /axios\.(post|put)\s*\(|fetch\s*\([^)]*method\s*:\s*['"]POST|node-fetch|got\.(post|put)/,
    fileExtensions: ['js', 'ts', 'jsx', 'tsx'],
  },
  {
    id: 'data_exfil_curl',
    category: 'exfiltration',
    severity: 'high',
    name: 'Data exfiltration (curl/wget)',
    description: 'Sends data using command-line HTTP tools',
    regex: /curl\s+.*--data|curl\s+.*-d\s|wget\s+.*--post-data/,
    fileExtensions: ['sh', 'bash', 'zsh', 'md'],
  },
  {
    id: 'context_leakage_env',
    category: 'exfiltration',
    severity: 'high',
    name: 'Context leakage (dotfiles)',
    description: 'Reads sensitive configuration files from home directory',
    regex: /~\/\.env\b|~\/\.bashrc|~\/\.zshrc|~\/\.profile|~\/\.bash_history/,
    fileExtensions: ALL_EXTENSIONS,
  },
  {
    id: 'context_leakage_memory',
    category: 'exfiltration',
    severity: 'high',
    name: 'Context leakage (agent memory)',
    description: 'Reads agent memory files which may contain sensitive context',
    regex: /(?:read|cat|open|load)\s*.*(?:SOUL|MEMORY|IDENTITY|OPERATIONS)\.md/i,
    fileExtensions: ALL_EXTENSIONS,
  },
];
