import type { ThreatPattern } from './types.js';
import { ALL_EXTENSIONS, CODE_EXTENSIONS } from '../types.js';

export const persistencePatterns: ThreatPattern[] = [
  {
    id: 'memory_poison',
    category: 'persistence',
    severity: 'critical',
    name: 'Agent memory poisoning',
    description: 'Modifies agent memory/identity files (AGENTS.md, SOUL.md, MEMORY.md)',
    regex: /(?:write|modify|append|echo|cat|sed|tee)\s+.*>>\s*.*(?:AGENTS|SOUL|MEMORY|OPERATIONS|IDENTITY)\.md/i,
    fileExtensions: ALL_EXTENSIONS,
  },
  {
    id: 'memory_poison_redirect',
    category: 'persistence',
    severity: 'critical',
    name: 'Agent memory file redirect',
    description: 'Redirects output to agent memory files',
    regex: />\s*(?:\.\/|\/)?(?:AGENTS|SOUL|MEMORY|OPERATIONS|IDENTITY)\.md/i,
    fileExtensions: ALL_EXTENSIONS,
  },
  {
    id: 'reverse_shell_tcp',
    category: 'persistence',
    severity: 'critical',
    name: 'Reverse shell (/dev/tcp)',
    description: 'Opens a reverse shell via /dev/tcp',
    regex: /\/dev\/tcp\/\S+\/\d+|bash\s+-i\s+>&\s*\/dev\/tcp/,
    fileExtensions: ALL_EXTENSIONS,
  },
  {
    id: 'reverse_shell_nc',
    category: 'persistence',
    severity: 'critical',
    name: 'Reverse shell (netcat)',
    description: 'Opens a reverse shell via netcat',
    regex: /\bnc\s+(?:-e|-c)\s|ncat\s+.*(?:-e|-c)\s|mkfifo\s+.*\bnc\b/,
    fileExtensions: ALL_EXTENSIONS,
  },
  {
    id: 'reverse_shell_python',
    category: 'persistence',
    severity: 'critical',
    name: 'Reverse shell (Python)',
    description: 'Opens a reverse shell via Python socket',
    regex: /socket\.socket.*connect.*subprocess|import\s+pty\s*;?\s*pty\.spawn/,
    fileExtensions: ['py'],
  },
  {
    id: 'nohup_background',
    category: 'persistence',
    severity: 'medium',
    name: 'Background process persistence',
    description: 'Starts background processes that persist after skill execution',
    regex: /nohup\s+.*(?:bash|sh|python|node)\s+.*&|disown\b|setsid\s+.*(?:bash|sh)/,
    fileExtensions: ALL_EXTENSIONS,
  },
  {
    id: 'cron_persistence',
    category: 'persistence',
    severity: 'critical',
    name: 'Cron job persistence',
    description: 'Installs a cron job for persistent execution',
    regex: /crontab\s+|\/etc\/cron|echo\s+.*>>\s*.*crontab/,
    fileExtensions: ALL_EXTENSIONS,
  },
  {
    id: 'startup_persistence',
    category: 'persistence',
    severity: 'critical',
    name: 'Startup script persistence',
    description: 'Modifies startup scripts for persistent execution',
    regex: />>?\s*~\/\.(?:bashrc|zshrc|profile|bash_profile)|\/etc\/(?:rc\.local|init\.d)/,
    fileExtensions: ALL_EXTENSIONS,
  },
];
