import type { ThreatPattern } from './types.js';
import { ALL_EXTENSIONS, CODE_EXTENSIONS } from '../types.js';

export const privilegePatterns: ThreatPattern[] = [
  {
    id: 'sudo_escalation',
    category: 'privilege_escalation',
    severity: 'high',
    name: 'Sudo/root escalation',
    description: 'Attempts to run commands with elevated privileges',
    regex: /sudo\s+\S|chmod\s+[0-7]{3,4}\s|chown\s+\S|setuid|setgid/,
    fileExtensions: ['sh', 'bash', 'zsh', 'py', 'rb'],
  },
  {
    id: 'credential_access_ssh',
    category: 'privilege_escalation',
    severity: 'high',
    name: 'SSH credential access',
    description: 'Accesses SSH keys or configuration',
    regex: /~\/\.ssh\b|\.ssh\/id_|\.ssh\/authorized_keys|\.ssh\/config\b/,
    fileExtensions: ALL_EXTENSIONS,
  },
  {
    id: 'credential_access_cloud',
    category: 'privilege_escalation',
    severity: 'high',
    name: 'Cloud credential access',
    description: 'Accesses cloud provider credentials',
    regex: /~\/\.aws\b|~\/\.config\/gcloud|~\/\.kube\/config|~\/\.docker\/config\.json|~\/\.azure\b/,
    fileExtensions: ALL_EXTENSIONS,
  },
  {
    id: 'credential_access_package',
    category: 'privilege_escalation',
    severity: 'high',
    name: 'Package manager credential access',
    description: 'Accesses package manager authentication files',
    regex: /\.npmrc\b|\.pypirc\b|\.netrc\b|\.git-credentials\b|\.pgpass\b|\.mysql_history\b/,
    fileExtensions: ALL_EXTENSIONS,
  },
  {
    id: 'credential_access_keychain',
    category: 'privilege_escalation',
    severity: 'high',
    name: 'Keychain/keystore access',
    description: 'Accesses system keychain or credential store',
    regex: /keychain\b|security\s+find-generic-password|credman|credential\s*manager/i,
    fileExtensions: ALL_EXTENSIONS,
  },
  {
    id: 'allowed_tools_excessive',
    category: 'privilege_escalation',
    severity: 'high',
    name: 'Excessive tool permissions',
    description: 'Requests dangerous tool access (Bash, exec, Write, system)',
    regex: /allowed.?tools\s*:.*\b(Bash|Computer|exec|shell|system|Write)\b/i,
    fileExtensions: ['md', 'yaml', 'yml', 'json'],
  },
  {
    id: 'docker_socket',
    category: 'privilege_escalation',
    severity: 'critical',
    name: 'Docker socket access',
    description: 'Accesses Docker socket which grants root-equivalent privileges',
    regex: /\/var\/run\/docker\.sock|docker\.sock\b/,
    fileExtensions: ALL_EXTENSIONS,
  },
  {
    id: 'proc_access',
    category: 'privilege_escalation',
    severity: 'high',
    name: '/proc filesystem access',
    description: 'Accesses process information which can leak sensitive data',
    regex: /\/proc\/\d+|\/proc\/self\b|\/proc\/version\b/,
    fileExtensions: ALL_EXTENSIONS,
  },
  {
    id: 'subprocess_python',
    category: 'privilege_escalation',
    severity: 'high',
    name: 'Subprocess execution (Python)',
    description: 'Executes commands via Python subprocess or os module',
    regex: /subprocess\.(run|Popen|call|check_call|check_output)\s*\(|os\.(system|popen|exec[lv]p?e?)\s*\(/,
    fileExtensions: ['py'],
  },
  {
    id: 'child_process_node',
    category: 'privilege_escalation',
    severity: 'high',
    name: 'Child process execution (Node.js)',
    description: 'Imports or uses child_process for command execution',
    regex: /child_process\b|execSync\s*\(|execFileSync\s*\(|spawnSync\s*\(/,
    fileExtensions: ['js', 'ts', 'jsx', 'tsx'],
  },
  {
    id: 'shell_exec_generic',
    category: 'privilege_escalation',
    severity: 'high',
    name: 'Shell command execution (generic)',
    description: 'Executes shell commands via runtime APIs',
    regex: /Deno\.run\s*\(|Bun\.spawn\s*\(|Runtime\.getRuntime\(\)\.exec/,
    fileExtensions: CODE_EXTENSIONS,
  },
];
