import type { ThreatPattern } from './types.js';
import { ALL_EXTENSIONS, MARKDOWN_EXTENSIONS } from '../types.js';

export const promptInjectionPatterns: ThreatPattern[] = [
  {
    id: 'instruction_override',
    category: 'prompt_injection',
    severity: 'critical',
    name: 'Instruction override',
    description: 'Attempts to override or ignore previous instructions',
    regex: /ignore\s+(?:all\s+)?(?:previous|prior|above)\s+instructions|disregard\s+(?:all\s+)?(?:previous|prior|above)|forget\s+(?:all\s+)?(?:your\s+)?(?:previous\s+)?instructions/i,
    fileExtensions: ALL_EXTENSIONS,
  },
  {
    id: 'instruction_override_new',
    category: 'prompt_injection',
    severity: 'critical',
    name: 'New instruction injection',
    description: 'Attempts to inject new system-level instructions',
    regex: /new\s+instructions?\s*:|system\s+prompt\s*:|you\s+are\s+now\s+(?:a|an|the)\b|your\s+new\s+(?:role|instructions?|task)\s+is/i,
    fileExtensions: ALL_EXTENSIONS,
  },
  {
    id: 'persona_override',
    category: 'prompt_injection',
    severity: 'high',
    name: 'Persona/role override',
    description: 'Attempts to override AI persona or role',
    regex: /act\s+as\s+(?:if\s+you\s+are|a|an)|pretend\s+(?:to\s+be|you\s+are)|you\s+must\s+(?:always|never)\s+(?:respond|answer|say)|do\s+anything\s+now|DAN\s+mode/i,
    fileExtensions: ALL_EXTENSIONS,
  },
  {
    id: 'hidden_text_unicode',
    category: 'prompt_injection',
    severity: 'critical',
    name: 'Hidden Unicode directives',
    description: 'Uses zero-width or invisible Unicode characters to hide content',
    regex: /[\u200B\u200C\u200D\uFEFF\u2060\u00AD]|[\u202A-\u202E]|[\u2066-\u2069]/,
    fileExtensions: ALL_EXTENSIONS,
  },
  {
    id: 'hidden_text_html',
    category: 'prompt_injection',
    severity: 'high',
    name: 'Hidden HTML directives',
    description: 'Uses HTML comments or invisible elements to hide instructions',
    regex: /<!--\s*(?:system|instruction|ignore|override|hidden)[^>]*-->|<(?:div|span)\s+style\s*=\s*["'][^"']*(?:display\s*:\s*none|visibility\s*:\s*hidden|font-size\s*:\s*0)/i,
    fileExtensions: ['md', 'html', 'htm'],
  },
  {
    id: 'exfil_command_send',
    category: 'prompt_injection',
    severity: 'high',
    name: 'Exfiltration command in text',
    description: 'Instructs AI to send/forward data to external destinations',
    regex: /send\s+(?:the\s+)?(?:contents?|data|results?|output)\s+(?:to|via)\s+\S+|forward\s+(?:this|the|all)\s+(?:to|via)\s+\S+|email\s+.*\s+to\s+\S+@\S+/i,
    fileExtensions: ALL_EXTENSIONS,
  },
  {
    id: 'exfil_command_encode',
    category: 'prompt_injection',
    severity: 'high',
    name: 'Data encoding for exfiltration',
    description: 'Instructs encoding data (base64, URL params) for covert exfil',
    regex: /encode\s+(?:the\s+)?(?:response|output|data)\s+(?:as|in|to)\s+base64|append\s+.*\s+(?:to|as)\s+(?:url|query)\s+param/i,
    fileExtensions: ALL_EXTENSIONS,
  },
  {
    id: 'safety_bypass',
    category: 'prompt_injection',
    severity: 'critical',
    name: 'Safety filter bypass',
    description: 'Attempts to bypass AI safety measures or content filters',
    regex: /jailbreak|bypass\s+(?:safety|content|security)\s+(?:filter|check|guard)|disable\s+(?:safety|content)\s+(?:filter|mode)|unlock\s+(?:full|unrestricted)\s+(?:mode|access)/i,
    fileExtensions: ALL_EXTENSIONS,
  },
  {
    id: 'prompt_leak',
    category: 'prompt_injection',
    severity: 'high',
    name: 'System prompt extraction',
    description: 'Attempts to extract or reveal system prompt',
    regex: /(?:print|show|reveal|display|output|repeat)\s+(?:your\s+)?(?:system\s+)?(?:prompt|instructions?|rules)/i,
    fileExtensions: ALL_EXTENSIONS,
  },
  {
    id: 'indirect_injection',
    category: 'prompt_injection',
    severity: 'high',
    name: 'Indirect prompt injection',
    description: 'Embeds instructions in data fields meant to be processed by AI',
    regex: /\[INST\]|\[\/INST\]|<\|(?:system|user|assistant)\|>|<\/?(?:system|user|assistant)>/,
    fileExtensions: ALL_EXTENSIONS,
  },
  {
    id: 'tool_force',
    category: 'prompt_injection',
    severity: 'high',
    name: 'Forced tool invocation',
    description: 'Attempts to force AI to invoke specific tools',
    regex: /you\s+must\s+(?:call|use|invoke|run)\s+(?:the\s+)?(?:tool|function|command)|execute\s+(?:the\s+)?(?:following|this)\s+(?:tool|command|function)\s+immediately/i,
    fileExtensions: ALL_EXTENSIONS,
  },
];
