import type { ThreatPattern } from './types.js';
import { CODE_EXTENSIONS, ALL_EXTENSIONS } from '../types.js';

export const supplyChainPatterns: ThreatPattern[] = [
  {
    id: 'unpinned_deps_pip',
    category: 'supply_chain',
    severity: 'medium',
    name: 'Unpinned pip dependency',
    description: 'Installs Python package without version pinning',
    regex: /pip\s+install\s+(?!.*==)(?!.*-r\s)(?!-e\s)\S+/,
    fileExtensions: ['sh', 'bash', 'zsh', 'md', 'py'],
  },
  {
    id: 'unpinned_deps_npm',
    category: 'supply_chain',
    severity: 'medium',
    name: 'Unpinned npm dependency',
    description: 'Installs Node.js package without version pinning',
    regex: /npm\s+install\s+(?!.*@\d)(?!--save-dev)(?!-D)\S+/,
    fileExtensions: ['sh', 'bash', 'zsh', 'md', 'json'],
  },
  {
    id: 'script_fetch_curl',
    category: 'supply_chain',
    severity: 'critical',
    name: 'Remote script execution (curl|sh)',
    description: 'Downloads and executes remote script — classic supply chain attack',
    regex: /curl\s+.*\|\s*(?:ba)?sh|wget\s+.*\|\s*(?:ba)?sh|curl\s+.*-o\s+\S+.*&&\s*(?:ba)?sh/,
    fileExtensions: ALL_EXTENSIONS,
  },
  {
    id: 'script_fetch_python',
    category: 'supply_chain',
    severity: 'critical',
    name: 'Remote script execution (Python)',
    description: 'Downloads and executes remote code in Python',
    regex: /(?:requests|urllib|httpx)\.get\s*\([^)]+\).*exec|eval\s*\(\s*(?:requests|urllib)\.get/,
    fileExtensions: ['py'],
  },
  {
    id: 'script_fetch_node',
    category: 'supply_chain',
    severity: 'critical',
    name: 'Remote script execution (Node.js fetch)',
    description: 'Downloads and evaluates remote code in JavaScript',
    regex: /fetch\s*\([^)]+\).*\.then\s*\([^)]*eval|eval\s*\(\s*await\s+fetch/,
    fileExtensions: ['js', 'ts', 'jsx', 'tsx'],
  },
  {
    id: 'script_fetch_https',
    category: 'supply_chain',
    severity: 'critical',
    name: 'Remote script execution (https module)',
    description: 'Downloads remote code via https.get/request and executes with eval',
    regex: /https?\.(get|request)\([^)]*\)[\s\S]{0,200}eval\(/,
    fileExtensions: ['js', 'ts', 'jsx', 'tsx'],
  },
  {
    id: 'obfuscated_exec_python',
    category: 'supply_chain',
    severity: 'critical',
    name: 'Obfuscated code execution (Python)',
    description: 'Executes obfuscated or dynamically constructed code',
    regex: /exec\s*\(.*zlib\.decompress|zlib\.decompress.*exec|compile\s*\([^)]+\)\s*.*exec|__import__\s*\(\s*['"]os['"]\)/,
    fileExtensions: ['py'],
  },
  {
    id: 'obfuscated_exec_node',
    category: 'supply_chain',
    severity: 'critical',
    name: 'Obfuscated code execution (Node.js)',
    description: 'Evaluates dynamically constructed code',
    regex: /eval\s*\(\s*(?:atob|Buffer\.from)\s*\(|new\s+Function\s*\(\s*(?:atob|Buffer\.from)/,
    fileExtensions: ['js', 'ts', 'jsx', 'tsx'],
  },
  {
    id: 'base64_pipe',
    category: 'supply_chain',
    severity: 'critical',
    name: 'Base64 decode to shell execution',
    description: 'Decodes base64 content and pipes to shell interpreter',
    regex: /base64\s+(?:-d|-D|--decode)\s*\|\s*(?:bash|sh|zsh|python|perl|ruby)/,
    fileExtensions: ALL_EXTENSIONS,
  },
  {
    id: 'hex_decode_exec',
    category: 'supply_chain',
    severity: 'critical',
    name: 'Hex decode to execution',
    description: 'Decodes hex-encoded payload and executes it',
    regex: /xxd\s+-r.*\|\s*(?:bash|sh)|python.*\\x[0-9a-f]{2}.*exec|bytes\.fromhex.*exec/i,
    fileExtensions: ALL_EXTENSIONS,
  },
  {
    id: 'pep723_unpinned',
    category: 'supply_chain',
    severity: 'medium',
    name: 'PEP 723 unpinned dependency',
    description: 'PEP 723 inline script metadata with unpinned dependencies',
    regex: /# \/\/\/\s*script|dependencies\s*=\s*\[/,
    fileExtensions: ['py'],
  },
  {
    id: 'install_script_hook',
    category: 'supply_chain',
    severity: 'high',
    name: 'Package install script hook',
    description: 'Package.json defines install/preinstall hooks that run arbitrary code',
    regex: /"(?:pre|post)?install"\s*:\s*"[^"]*(?:sh |bash |node |python )/,
    fileExtensions: ['json'],
  },
  {
    id: 'dynamic_require',
    category: 'supply_chain',
    severity: 'high',
    name: 'Dynamic require/import',
    description: 'Dynamically loads modules from computed paths',
    regex: /require\s*\(\s*(?!['"])[^)]+\)|import\s*\(\s*(?!['"])[^)]+\)/,
    fileExtensions: ['js', 'ts', 'jsx', 'tsx'],
  },
];
